services:
  - type: web
    name: warranty-bot
    env:
  PYTHON_VERSION: "3.12.3"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: WEBHOOK_URL
        fromEnvVar: WEBHOOK_URL
